// lib/data.ts – Static data for portfolio

export const personalInfo = {
  name: "Denys Stolyk",
  handle: "YouK1ch",
  title: "Cybersecurity Student & Researcher",
  subtitle: "3rd-year Cadet · KNUIA · Future SOC / Red Team Engineer",
  university: "Kharkiv National University of Internal Affairs (KNUIA)",
  year: "3rd Year",
  location: "Kharkiv, Ukraine",
  email: "deni.s201811111111@gmail.com",
  github: "https://github.com/YouK1ch",
  tryhackme: "https://tryhackme.com/p/Yuk1ch",
  hackthebox: "https://app.hackthebox.com/public/users/1960165",
  bio: [
    "Cybersecurity cadet with a deep passion for offensive and defensive security. I believe the best defenders are those who think like attackers.",
    "My journey spans network analysis, OSINT, web exploitation, and infrastructure security. Currently sharpening skills on TryHackMe and HackTheBox while pursuing my degree at KNUIA.",
    "Career goal: Become a threat hunter and security engineer capable of designing resilient systems and dismantling adversarial infrastructure.",
  ],
  goals: [
    { icon: "🎯", label: "SOC Analyst", desc: "Threat detection & incident response" },
    { icon: "🔴", label: "Red Team", desc: "Offensive security & penetration testing" },
    { icon: "🛡️", label: "Security Engineer", desc: "Secure system design & architecture" },
  ],
};

export const skills = [
  {
    category: "Offensive Security",
    color: "#ff6b35",
    icon: "⚔️",
    items: [
      { name: "Penetration Testing", level: 70 },
      { name: "Web Application Hacking", level: 72 },
      { name: "OSINT", level: 78 },
      { name: "Network Exploitation", level: 65 },
      { name: "Privilege Escalation", level: 62 },
    ],
  },
  {
    category: "Defensive Security",
    color: "#00ff88",
    icon: "🛡️",
    items: [
      { name: "Network Analysis", level: 75 },
      { name: "Log Analysis & SIEM", level: 60 },
      { name: "Incident Response", level: 58 },
      { name: "Threat Intelligence", level: 63 },
      { name: "Malware Analysis", level: 55 },
    ],
  },
  {
    category: "Tools & Platforms",
    color: "#00f5ff",
    icon: "🔧",
    items: [
      { name: "Wireshark", level: 80 },
      { name: "Metasploit", level: 65 },
      { name: "Burp Suite", level: 70 },
      { name: "Nmap / Nessus", level: 75 },
      { name: "Kali Linux", level: 82 },
    ],
  },
  {
    category: "Programming & DevOps",
    color: "#b347ff",
    icon: "💻",
    items: [
      { name: "Python (scripting/automation)", level: 70 },
      { name: "Bash / Shell", level: 75 },
      { name: "Linux Administration", level: 78 },
      { name: "Docker", level: 55 },
      { name: "SQL", level: 60 },
    ],
  },
];

export const tryhackmeData = {
  username: "Yuk1ch",
  rank: "0x4 [Hacker]",
  points: 1840,
  roomsCompleted: 46,
  badges: 12,
  streak: 14,
  globalRank: "Top 8%",
  profileUrl: "https://tryhackme.com/p/Yuk1ch",
  badgeUrl: "https://tryhackme-badges.s3.amazonaws.com/Yuk1ch.png",
  completedRooms: [
    "OWASP Top 10",
    "Linux Fundamentals",
    "Network Services",
    "Metasploit",
    "Hydra",
    "Nmap",
    "Burp Suite Basics",
    "John The Ripper",
    "Pickle Rick",
    "Pre-Security Path",
  ],
};

export const hacktheboxData = {
  username: "Yuk1ch",
  userId: 1960165,
  rank: "Script Kiddie → Hacker",
  points: 420,
  machinesSolved: 8,
  challengesSolved: 12,
  globalRank: "Top 15%",
  profileUrl: "https://app.hackthebox.com/public/users/1960165",
  respect: 34,
  color: "#9fef00",
};

export const certifications = [
  {
    name: "Ethical Hacker",
    issuer: "Cisco Networking Academy",
    date: "Jun 12, 2024",
    type: "Certificate",
    color: "#049fd9",
    icon: "🔴",
    category: "Security",
  },
  {
    name: "Introduction to Ethical Hacking",
    issuer: "Cisco Networking Academy",
    date: "Apr 21, 2024",
    type: "Achievement",
    color: "#049fd9",
    icon: "🎯",
    category: "Security",
  },
  {
    name: "Вступ до кібербезпеки",
    issuer: "Cisco Networking Academy",
    date: "Mar 27, 2026",
    type: "Certificate",
    color: "#049fd9",
    icon: "🔐",
    category: "Security",
  },
  {
    name: "Network Support and Security",
    issuer: "Cisco Networking Academy",
    date: "Nov 18, 2025",
    type: "Certificate",
    color: "#049fd9",
    icon: "🌐",
    category: "Networking",
  },
  {
    name: "Network Addressing and Basic Troubleshooting",
    issuer: "Cisco Networking Academy",
    date: "Nov 18, 2025",
    type: "Certificate",
    color: "#049fd9",
    icon: "🔗",
    category: "Networking",
  },
  {
    name: "Мережні пристрої та початкове налаштування",
    issuer: "Cisco Networking Academy",
    date: "Nov 18, 2025",
    type: "Badge",
    color: "#049fd9",
    icon: "📡",
    category: "Networking",
  },
  {
    name: "Networking Basics",
    issuer: "Cisco Networking Academy",
    date: "Nov 17, 2025",
    type: "Certificate",
    color: "#049fd9",
    icon: "🌐",
    category: "Networking",
  },
  {
    name: "Operating Systems Basics",
    issuer: "Cisco Networking Academy",
    date: "Nov 07, 2025",
    type: "Certificate",
    color: "#049fd9",
    icon: "🖥️",
    category: "Systems",
  },
  {
    name: "Computer Hardware Basics",
    issuer: "Cisco Networking Academy",
    date: "Nov 07, 2025",
    type: "Certificate",
    color: "#049fd9",
    icon: "💾",
    category: "Systems",
  },
  {
    name: "Початок роботи з Cisco Packet Tracer",
    issuer: "Cisco Networking Academy",
    date: "Mar 06, 2025",
    type: "Achievement",
    color: "#049fd9",
    icon: "🛠️",
    category: "Networking",
  },
];

export const navLinks = [
  { href: "#hero", label: "Home" },
  { href: "#about", label: "About" },
  { href: "#skills", label: "Skills" },
  { href: "#tryhackme", label: "TryHackMe" },
  { href: "#hackthebox", label: "HackTheBox" },
  { href: "#cisco", label: "Cisco" },
  { href: "#contact", label: "Contact" },
];
